// =========================
// DADOS COMPLEMENTARES DAS ESCOLAS
// =========================
const ESCOLAS_DADOS = {
  "CEEFMTI Afonso Cláudio": {
    city: "Afonso Cláudio",
    director: "Allan Dyoni Dehete Many"
  },
  "CEEFMTI Elisa Paiva": {
    city: "Conceição do Castelo",
    director: "Rosangela Vargas Davel Pinto"
  },
  "EE Ivana Casagrande Scabelo": {
    city: "Venda Nova do Imigrante",
    director: "Maristela Broedel"
  },
  "EE Severino Paste": {
    city: "Venda Nova do Imigrante",
    director: "Maristela Broedel"
  },
  "EEEFM Alto Rio Possmoser": {
    city: "Santa Maria de Jetibá",
    director: "Adriana da Conceição Tesch"
  },
  "EEEFM Álvaro Castelo": {
    city: "Brejetuba",
    director: "Rose Fabrícia Moretto"
  },
  "EEEFM Domingos Perim": {
    city: "Venda Nova do Imigrante",
    director: "Maristela Broedel"
  },
  "EEEFM Elvira Barros": {
    city: "Afonso Cláudio",
    director: "Andrea Gomes Klug"
  },
  "EEEFM Fazenda Camporês": {
    city: "Brejetuba",
    director: "Emerson Ungarato"
  },
  "EEEFM Fazenda Emílio Schroeder": {
    city: "Santa Maria de Jetibá",
    director: "Jorge Schneider"
  },
  "EEEFM Fioravante Caliman": {
    city: "Venda Nova do Imigrante",
    director: "Celina Januário Moreira"
  },
  "EEEFM Frederico Boldt": {
    city: "Santa Maria de Jetibá",
    director: "David Felberg"
  },
  "EEEFM Gisela Salloker Fayet": {
    city: "Domingos Martins",
    director: "Maxwel Augusto Neves"
  },
  "EEEFM Graça Aranha": {
    city: "Santa Maria de Jetibá",
    director: "Camilo Pauli Dominicini"
  },
  "EEEFM Joaquim Caetano de Paiva": {
    city: "Laranja da Terra",
    director: "Miriam Klitzke Seibel"
  },
  "EEEFM José Cupertino": {
    city: "Afonso Cláudio",
    director: "Cléria Pagotto Ronchi Zanelato"
  },
  "EEEFM José Giestas": {
    city: "Afonso Cláudio",
    director: "Gederson Vargas Dazilio"
  },
  "EEEFM José Roberto Christo": {
    city: "Afonso Cláudio",
    director: "Andressa Silva Dias"
  },
  "EEEFM Leogildo Severiano de Souza": {
    city: "Brejetuba",
    director: "Adalberto Carlos Araújo Chaves"
  },
  "EEEFM Luiz Jouffroy": {
    city: "Laranja da Terra",
    director: "Nilza Abel Gumz"
  },
  "EEEFM Maria de Abreu Alvim": {
    city: "Afonso Cláudio",
    director: "Maria das Graças Fabio Costa"
  },
  "EE Mário Bergamin": {
    city: "Venda Nova do Imigrante",
    director: "Celina Januário Moreira"  
  },
  "EEEFM Marlene Brandão": {
    city: "Brejetuba",
    director: "Paulynne Ayres Tatagiba Gonçalves"
  },
  "EEEFM Pedra Azul": {
    city: "Domingos Martins",
    director: "Elizabeth Drumond Ambrósio Filgueiras"
  },
  "EEEFM Ponto do Alto": {
    city: "Domingos Martins",
    director: "Marcelo Ribett"
  },
  "EEEFM Profª Aldy Soares Merçon Vargas": {
    city: "Conceição do Castelo",
    director: "Israel Augusto Moreira Borges"
  },
  "EEEFM Prof Hermann Berger": {
    city: "Santa Maria de Jetibá",
    director: "Eliane Raasch Bicalho"
  },
  "EEEFM São Jorge": {
    city: "Brejetuba",
    director: "Jormi Maria da Silva"
  },
  "EEEFM São Luís": {
    city: "Santa Maria de Jetibá",
    director: "Valdirene Mageski Cordeiro Magri"
  },
  "EEEFM Teófilo Paulino": {
    city: "Domingos Martins",
    director: "Delfina Schneider Stein"
  },
  "EEEM Francisco Guilherme": {
    city: "Santa Maria de Jetibá",
    director: "Jonatas André Drescher"
  },
  "EEEM Mata fria": {
    city: "Afonso Cláudio",
    director: "Jonatas André Drescher"
  },
  "EEEFM Tutorial Teste": {
    city: "Afonso Cláudio",
    director: "Diretor Teste"
  },
  "EEEM Sobreiro": {
    city: "Laranja da Terra",
    director: "Jonatas André Drescher"
  }
};
// =========================
// ATOS AUTORIZATIVOS – DADOS DE APOIO
// =========================

const CURSOS_ETAPAS = [
  "ENSINO MÉDIO - TEMPO PARCIAL",
  "ENSINO MÉDIO - TEMPO INTEGRAL",
  "ENSINO FUNDAMENTAL - TEMPO PARCIAL - ANOS INICIAIS",
  "ENSINO FUNDAMENTAL - TEMPO PARCIAL - ANOS FINAIS",
  "ENSINO FUNDAMENTAL - TEMPO INTEGRAL",
  "ENSINO FUNDAMENTAL - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA",
  "ENSINO FUNDAMENTAL - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO",
  "ENSINO MÉDIO - EJA",
  "ENSINO MÉDIO - EJA - EDUCAÇÃO ESCOLAR INDÍGENA",
  "ENSINO MÉDIO – EJA - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA",
  "ENSINO MÉDIO - EJA - EDUCAÇÃO DO CAMPO",
  "ENSINO MÉDIO - EDUCAÇÃO QUILOMBOLA",
  "ENSINO MÉDIO - EDUCAÇÃO ESCOLAR INDÍGENA",
  "ENSINO MÉDIO - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA",
  "ENSINO MÉDIO - EDUCAÇÃO DO CAMPO",
  "ENSINO FUNDAMENTAL - EJA - 1º SEGMENTO",
  "ENSINO FUNDAMENTAL - EJA - 2º SEGMENTO",
  "ENSINO FUNDAMENTAL - EJA - EDUCAÇÃO ESCOLAR INDÍGENA",
  "ENSINO FUNDAMENTAL - EJA - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA",
  "ENSINO FUNDAMENTAL - EJA - EDUCAÇÃO DO CAMPO",
  "ENSINO FUNDAMENTAL - EDUCAÇÃO ESCOLAR QUILOMBOLA",
  "ENSINO FUNDAMENTAL - EDUCAÇÃO ESCOLAR INDÍGENA",
  "ENSINO FUNDAMENTAL - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA",
  "ENSINO FUNDAMENTAL - EDUCAÇÃO DO CAMPO",
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – TEMPO INTEGRAL",
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO",
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO EM REGIME DE ALTERNÂNCIA",
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - EJA",
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – EDUCAÇÃO DE CAMPO - PEDAGOGIA DA ALTERNÂNCIA",
  "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
];

const FUNDAMENTACOES_POR_CURSO = {
  "ENSINO MÉDIO - TEMPO PARCIAL": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO - TEMPO INTEGRAL": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - TEMPO PARCIAL - ANOS INICIAIS": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CEE/ES Nº 3.777/2014 E RESOLUÇÃO CEE-ES Nº 5.190/2018."
  ],
  "ENSINO FUNDAMENTAL - TEMPO PARCIAL - ANOS FINAIS": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CEE/ES Nº 3.777/2014 E RESOLUÇÃO CEE-ES Nº 5.190/2018."
  ],
  "ENSINO FUNDAMENTAL - TEMPO INTEGRAL": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP Nº 01/2023; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CEB Nº 7/2010; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO - EJA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CEB Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO - EJA - EDUCAÇÃO ESCOLAR INDÍGENA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CEB/CNE Nº 5/2012; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CEB/CNE Nº 5/2012; RESOLUÇÃO CNE/CEB Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO – EJA - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP Nº 01/2023; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP N° 01/2023; RESOLUÇÃO CNE/CEB Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO - EJA - EDUCAÇÃO DO CAMPO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO - EDUCAÇÃO QUILOMBOLA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CEB Nº 8/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CEB Nº 8/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO - EDUCAÇÃO ESCOLAR INDÍGENA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CEB/CNE Nº 5/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CEB/CNE Nº 5/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP Nº 01/2023; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP N° 01/2023; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO MÉDIO - EDUCAÇÃO DO CAMPO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EJA - 1º SEGMENTO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EJA - 2º SEGMENTO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EJA - EDUCAÇÃO ESCOLAR INDÍGENA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 01/2021; RESOLUÇÃO CEB/CNE Nº 5/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEB/CNE Nº 5/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EJA - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP N° 01/2023; RESOLUÇÃO CNE/CEB Nº 01/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP Nº 01/2023; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EJA - EDUCAÇÃO DO CAMPO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 01/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EDUCAÇÃO ESCOLAR QUILOMBOLA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 8/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 8/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EDUCAÇÃO ESCOLAR INDÍGENA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CEB/CNE Nº 5/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CEB/CNE Nº 5/2012; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EDUCAÇÃO DO CAMPO - PEDAGOGIA DA ALTERNÂNCIA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP N° 01/2023; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP Nº 01/2023; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "ENSINO FUNDAMENTAL - EDUCAÇÃO DO CAMPO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CEB Nº 7/2010; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – TEMPO INTEGRAL": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CP Nº 1/2021; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CP Nº 1/2021; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CP Nº 1/2021; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO EM REGIME DE ALTERNÂNCIA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CP Nº 1/2021; RESOLUÇÃO CNE/CP Nº 01/2023; LEI ESTADUAL Nº 928/2019; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CP Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CP Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - EJA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 2/2024; RESOLUÇÃO CNE/CP Nº 1/2021; RESOLUÇÃO CNE/CEB Nº 3/2025; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CP Nº 1/2021; RESOLUÇÃO CNE/CEB Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – EDUCAÇÃO DE CAMPO - PEDAGOGIA DA ALTERNÂNCIA": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB Nº 3/2018; RESOLUÇÃO CNE/CEB Nº 2/2008; RESOLUÇÃO CNE/CP Nº 1/2021; RESOLUÇÃO CNE/CP Nº 01/2023; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ],
  "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE": [
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CEB N° 02/2020; RESOLUÇÃO CNE/CP Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014.",
    "LEI Nº 9.394/1996; RESOLUÇÃO CNE/CP Nº 1/2021; RESOLUÇÃO CEE/ES Nº 3.777/2014."
  ]
};

const CURSOS_TECNICOS = {
  "Técnico em Administração": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – TEMPO INTEGRAL",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - EJA"
  ],
  "Técnico em Agronegócio": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO EM REGIME DE ALTERNÂNCIA",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – EDUCAÇÃO DE CAMPO - PEDAGOGIA DA ALTERNÂNCIA"
  ],
  "Técnico em Agropecuária": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO EM REGIME DE ALTERNÂNCIA",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – EDUCAÇÃO DE CAMPO - PEDAGOGIA DA ALTERNÂNCIA"
  ],
  "Técnico em Cafeicultura": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – EDUCAÇÃO DE CAMPO - PEDAGOGIA DA ALTERNÂNCIA"
  ],
  "Técnico em Ciência de Dados": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Desenvolvimento de Sistemas": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – TEMPO INTEGRAL",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Edificações": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Eletrotécnica": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – TEMPO INTEGRAL",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Eletromecânica": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Estética": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Eventos": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Finanças": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Guia de Turismo": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Informática": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Informática para Internet": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – TEMPO INTEGRAL",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Logística": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - EJA"
  ],
  "Técnico em Manutenção e Suporte em Informática": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Mecânica": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Meio Ambiente": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO - TEMPO INTEGRAL - EDUCAÇÃO DO CAMPO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Metalurgia": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Mineração": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Nutrição e Dietética": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Portos": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Produção de Moda": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Programação de Jogos Digitais": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – TEMPO INTEGRAL"
  ],
  "Técnico em Química": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Recursos Humanos": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Redes de Computadores": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Segurança do Trabalho": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Serviços Jurídicos": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Sistemas de Energia Renovável": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA INTEGRADA AO ENSINO MÉDIO – TEMPO INTEGRAL",
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ],
  "Técnico em Transações Imobiliárias": [
    "EDUCAÇÃO PROFISSIONAL TÉCNICA DE NÍVEL MÉDIO - CONCOMITANTE E SUBSEQUENTE"
  ]
};
